# Generated by Django 4.2.7 on 2025-09-29 10:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('married', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5)),
                ('dependents', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3+', '3+')], max_length=5)),
                ('education', models.CharField(choices=[('Graduate', 'Graduate'), ('Not Graduate', 'Not Graduate')], max_length=20)),
                ('self_employed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5)),
                ('applicant_income', models.IntegerField()),
                ('coapplicant_income', models.IntegerField(default=0)),
                ('loan_amount', models.IntegerField()),
                ('loan_amount_term', models.IntegerField()),
                ('credit_history', models.BooleanField()),
                ('property_area', models.CharField(choices=[('Urban', 'Urban'), ('Semiurban', 'Semiurban'), ('Rural', 'Rural')], max_length=15)),
                ('loan_status', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('risk_level', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10, null=True)),
                ('approval_probability', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
