# Generated by Django 4.2.7 on 2025-10-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_predictor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanapplication',
            options={},
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='risk_level',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='dependents',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3+', '3+')], max_length=2),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_amount_term',
            field=models.IntegerField(default=360),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='married',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='property_area',
            field=models.CharField(choices=[('Urban', 'Urban'), ('Semiurban', 'Semiurban'), ('Rural', 'Rural')], max_length=10),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='self_employed',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
    ]
