# Generated by Django 4.2.7 on 2025-10-06 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_predictor', '0002_alter_loanapplication_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'Loan Application', 'verbose_name_plural': 'Loan Applications'},
        ),
    ]
